Correct tooltip when no battery
elementary/wingpanel-indicator-power pull request #181
Opened 2021-03-30 18:37 UTC by jeremypw

Fixes #172
* Handle failure of `upower.get_display_device ()
* Search for power supply amongst device list if necessary
* Always connect to change in display_device property
* Modify tooltip accordingly

2021-03-30 18:42 UTC, jeremypw commented
This only deals with the case where there are no other battery devices available to show in the icon or tooltip - but that is also the case for master.  A subsequent PR can deal with that.

2021-04-01 18:02 UTC, danrabbit requested changes
With this branch, on desktop, I get the following:
```
(null)
using an external power source
```

Which I'm not sure that the secondary text here is really useful because a desktop will always be using an external power source. And for a laptop, I think this implies that the battery is missing (otherwise it would show charge status) which is an error state.

2021-04-01 18:05 UTC, leonardo-lemos commented on src/Services/Device.vala
> +                    return _("Line Power");
"Plugged in" sounds more natural for me, I think it's easier to translate.

2021-04-01 22:12 UTC, jeremypw commented on src/Services/Device.vala
> +                    return _("Line Power");
OK, I'll change that.

2021-04-01 22:14 UTC, jeremypw commented
@danrabbit OK, it looks like we need to provide a fallback name for the device when it is null. Would "Plugged in" be appropriate?  Should the secondary text be omitted in this case?

2021-04-01 22:42 UTC, danrabbit commented
@jeremypw this is what I meant before about when we're plugged in that we're not really indicating the power status of the device, we're indicating the charge/discharge state of attached devices and/or peripherals

2021-04-06 18:54 UTC, jeremypw commented
The tooltip now just shows "Plugged in" instead of "Line Power".  I have not been able to test PR this with devices other than the built_in battery and the AC power supply on my laptop but if the UPower interface does not return a `display_device` then it tries to choose a suitable one from the list of devices returned by UPower, prioritizing batteries over power supplies.

No second line is shown for non-battery devices.  No tooltip is shown at all if the display_device device type is null.

2021-04-06 23:01 UTC, danrabbit commented
Hrm, I'm not really sure this is an improvement on desktop. Now, it feels like it's just picking a "random" device to represent battery. I have both a wireless mouse and keyboard plugged in, but for some reason the keyboard is the display device. That feels like a regression from the previous behavior

2021-04-07 09:02 UTC, jeremypw commented
@danrabbit OK, so would it be better to not try to second-guess `upower.get_display_device ()` and just suppress the tooltip if that function returns `null`?

2021-04-07 09:38 UTC, jeremypw commented
Now when the display device is `null` and a backlight is present, the tooltip shows info related to the screen brightness (which matches the icon used) otherwise there is no tooltip.

2021-04-20 16:54 UTC, jeremypw commented
@danrabbit Is this any better?  I am not really clear on what should be displayed (if anything) when the display device  returned by upower is `null`.

2021-04-20 20:58 UTC, danrabbit approved these changes
This all makes sense to me :) Thanks for being patient and working this out!

2021-04-20 20:58 UTC, merged